### ISSUE TITLE
Chained API for the Operands

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#106]
@pyu10055 proposed this idea in https://github.com/webmachinelearning/webnn/pull/94#discussion_r508056957

> ideally it would be great to allow chained api for the Operands.
builder.constant(...).add(builder.constant(...))

**Comment by huningxin** [comment]
Probably we could introduce the `interface mixin Operations` that has all the operation methods. Then the `ModelBuilder` and `Operand` could include it. Something like

```webidl
interface mixin Operations {
  Operand add(Operand a, Operand b);
  Operand sub(Operand a, Operand b);
  Operand mul(Operand a, Operand b);
  Operand div(Operand a, Operand b);
  // And other operations.
};

ModelBuilder includes Operations;
Operand includes Operations;
```

**Comment by pyu10055** [comment]
ModelBuilder operations should return ModelBuilder type

```
builder.constant(...).add(builder.constant(...)).build()
```

**Comment by pyu10055** [comment]
Using mixin looks good to me.

**Comment by wchao1115** [comment]
I'm not entirely clear about the problem we're trying to solve with this proposal. Can you elaborate?

**Comment by gramalingam** [comment]
Unclear how this will work. Chaining would require an interface with the first operand omitted, e.g. "Operand add(Operand b);" while the ModelBuilder requires operations with the first operand included. So, how can they share an interface? (Unless this is some special magic of the "mixin" feature in IDL.)

**Comment by huningxin** [comment]
@gramalingam , you are right, as the operations in `Operand` would use this operand as the first input, the `Operand` and `ModelBuilder` cannot share the operation definitions. The mixin interface doesn't help here.

**Comment by anssiko** [comment]
With no strong use case identified I propose we defer this for later.

I have [updated the 2021-01-07 agenda](https://github.com/webmachinelearning/meetings/commit/82bb05d12b8e1a646ec60a22bbddef7a59fd4dff) accordingly.

**Comment by fdwr** [comment]
🤔 How would this work with other operators that return multiple outputs like `split`/`gru`? Does this only make sense for unary and binary operators? Keeping the core WebNN API in SSA form feels more fundamental and generic, plus more consistent with most other ML libraries, but if someone wants a [method chaining (or "fluent interface")](https://en.wikipedia.org/wiki/Fluent_interface) helper atop WebNN, that's easy to wrap, right?

I love [UFCS](https://en.wikipedia.org/wiki/Uniform_function_call_syntax) in cases where it works nicely, but method chaining here introduces an inverted hierarchy, because now an `MLOperand` is effectively also an `MLGraphBuilder` (does it make sense for `MLOperand` to satisfy an "is a" relationship with `MLGraphBuilder`?).

It would be like calling `webgpuBuffer.setIndexBuffer(indexFormat, offset, size)` (from [`GPURenderBundleEncoder::setIndexBuffer(buffer, indexFormat, offset, size)`](https://developer.mozilla.org/en-US/docs/Web/API/GPURenderBundleEncoder/setIndexBuffer)) or `webgpuBuffer.copyBufferToTexture(destination, copySize)` (from [`GPUCommandEncoder::copyBufferToTexture(source, destination, copySize)`](https://developer.mozilla.org/en-US/docs/Web/API/GPUCommandEncoder/copyBufferToTexture)), but is any `GPUBuffer` implicitly also a `GPURenderBundleEncoder` and a `GPUCommandEncoder`?
