### ISSUE TITLE
Standardization process status

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [webmachinelearning/webnn#13]
Guys, wasn't sure where to post this issue so posting it here, but somebody please help me because I feel little lost:
 - where are we with standardization process?
 - what is left to do?
 - what decisions are to be made?

**Comment by anssiko** [comment]
Thanks for asking these questions. These process-y details can be daunting to people new to W3C. As the chair, I'll take care of these process details so that the group participants don't have to and they can focus on perhaps more exciting stuff that is technical discussion and solution engineering.

>* where are we with standardization process?

This work happens in a [W3C Community Group](https://www.w3.org/community/about/faq/#what-is-a-w3c-community-group) (CG). A CG provides an open forum for incubating ideas before they may advance to a [W3C Working Group](https://www.w3.org/2018/Process-20180201/#GroupsWG) (WG) for formal standardization. WGs follow a more rigid [W3C Technical Report Development Process](https://www.w3.org/2018/Process-20180201/#Reports) thus incubation is considered an important early phase to ensure ideas are proven before they advance to formal standardization. 

Within the incubation phase, the work typically proceeds as follows:
- [x] [charter](https://webmachinelearning.github.io/charter/) a CG, bring community together
- [x] identify [use cases](https://webmachinelearning.github.io/webnn/#usecases) aka the problems the group is interested in solving
- [ ] derive requirements, evaluate known solutions against the requirements (bonus: [explainer](https://github.com/w3ctag/w3ctag.github.io/blob/master/explainers.md))
- [ ] specify a solution that usually takes a form of a spec
- [ ] hand out the spec(s) to a WG for formal standardization

 >* what is left to do?

We've completed the first two steps above. The next step is to reach consensus on requirements, and continue evaluate known solutions. This discussion is happening in [open issues](https://github.com/webmachinelearning/webnn/issues).

>* what decisions are to be made?

The [open issues](https://github.com/webmachinelearning/webnn/issues) document issues that need to be resolved respecting the consensus of the group in order to advance. Since this work is early, we'll surely unearth more issues as we move along.

I suggest we keep this `webmachinelearning/webnn` repo focused on technical discussion. See also the [FAQ](https://www.w3.org/community/about/faq/) for more.
