### ISSUE TITLE
getNeuralNetworkContext() and createModelBuilder() params

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#135]
> 4. getNeuralNetworkContext() and createModelBuilder() seem strange (no parameters, for one thing) - is this expected to accept parameters/configs at some point? If so, we'd like to see what is intended here.

via https://github.com/w3ctag/design-reviews/issues/570#issuecomment-768875996

Per discussion the future eager mode would make use of the parameters.

**Comment by wchao1115** [comment]
A more substantial design point about the context vs. the model builder is that the context holds the states that apply globally across topologies that would be subsequently created while the model builder only holds the states that apply specifically to the current topology being constructed. Examples of the context states are device contexts, resource allocators, graph compilers, managed resource caches, etc. Examples of builder states are current topologies, graph designated inputs, transient or cached compilation states, cached compiled states, etc. Regardless of whether the methods are parameterless, this distinction persists.

Potential parameterization of the context includes device types (e.g. CPU, GPU, NPU, adaptive, etc.) For the model builder includes builder's state management (e.g. auto-resetting topology once construction finished), deferred or immediate execution (eager mode), hints for free-dimension inputs, etc.

**Comment by anssiko** [comment]
Nudge @cynthia :-)

**Comment by cynthia** [comment]
While I understand the intent, the pattern itself seems somewhat different from patterns in the wild. Tensorflow is the only framework that has this kind of design, where the closure in which the compute graph is constructed uses a context manager  (e,g. with tf.device) - other implementations construct and "transfer". (Pytorch, MXNet, and PaddlePaddle all seem to do this.)

I'm imagining something like this:

    const m = new ModelBuilder();
    
    // Do things with m... all of this probably happens in CPU-land.
    
    let context = getContext({device: "cuda0"'}) // If this fails, fallback to a different context?
    m.setContext({context: context}); // Setup transfer
    m.compile(); // If this fails (e.g. not enough device memory for co-processor), then probably need to fallback

**Comment by wchao1115** [comment]
Thanks @cynthia. We do not expose the notion of device explicitly in the API because in the context of the browser it could be challenging for the developers to know what type of device to target and which hardware platform the users will be having underneath.

For instance, although "GPU" can be specified more generically as a class of graphics devices, there are still vendor-specific GPU stacks (e.g. CUDA, ROcm, etc.) and the various NPU stacks (e.g. SNPE, OpenVino, etc.) that are also vendor-specific. This device selection and fallback logic could quickly become messy and complicated and result in poor/unexpected user experiences. The goal of WebNN is therefore to abstract the notion of concrete device types, while instead focusing on the user requirements concerning the type of model compilation the developers would favor over the others. This option is defined in the [PowerPreference](https://webmachinelearning.github.io/webnn/#api-model) enum, as a parameter to `Model.Compile`. It leaves the device selection and fallback policy up to the browser implementation.

On that note I'm still pondering if the `PowerPreference` should be specified as a parameter to the model compilation process or to the context creation itself; there are pros and cons on either approach. 

As for the original topic of this thread of whether we should define the construction of the model builder stylistically as the normal constructor method `new ModelBuilder(context)` or as a factory method `context.CreateModelBuilder()`, I tend to think in term of what type of info would be needed in the model builder construction process and whether those info can be obtained publicly through the context object.

According to the [Web Platform Design Principles](https://w3ctag.github.io/design-principles/#constructors) on usage of constructor. It claims:

> This won’t be appropriate in all cases. For example:
> - Some objects represent access to privileged resources, so they need to be constructed by factory methods which can access those resources.

In our specific case, I could imagine an implementation of `ModelBuilder` construction needing access to the underlying device encapsulated by but not publicly exposed through the `NeuralNetworkContext` class, and so, `context.CreateModelBuilder()` would be a more flexible contract for the implementer. Hope I clarify enough of my concern.

**Comment by wchao1115** [comment]
Although we do not expose the notion of the device, we do need the notion of the ML context so the implementer can host a device of any kind. And to successfully reuse the same underlying device from the WebGL rendering context or WebGPU, the ML context needs to be able to wrap them properly. Since it is quite important that the context facilitates the external device as well as the device that it creates on its own for the purpose of managing the device-specific resources that could be used as the ML model's constants (e.g. weights) as part of graph construction, the power preference should be moved back to the context, so device selection can be more upfront in the process, and is more inline with the device selection logic in WebGPU.

I've proposed this change in the PR #149 linked to this issue here.
