### ISSUE TITLE
Constructor or builder pattern for model building?

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#136]
> 5. Wouldn't it make sense to have a constructor rather than a builder pattern for createModelBuilder()? (e.g. new ModelBuilder(navigator.ml.getNNContext());

via https://github.com/w3ctag/design-reviews/issues/570#issuecomment-768875996

Early discussion suggests preference for the constructor. Some points brought up on the call today suggests we'll evaluate pros and cons here before committing.

**Comment by wchao1115** [comment]
@cynthia @anssiko A key benefit of a factory method over concrete construction e.g. `X.createY()` as opposed to `new Y(X)` is that the instantiation of the concrete type of `Y` can be internally parameterized and hidden away from the caller. This generally makes the API more robust over time since the implementor of `X` is free to instantiate `Y` as it sees fit. More specifically if we need `Y` to have multiple specializations, exposing `Y` as a constructible concrete type would then require the caller to know the types of every specializations of `Y` as `Y` evolves. In the context of the WebNN API, we believe that the notion of the *model builder* could have multiple concrete specializations depending on its execution mode (e.g. eager vs. deferred), and so the factory method makes it more flexible to evolve it over time.

**Comment by dontcallmedom** [comment]
for background, [design patterns for constructors in Web APIs](https://w3ctag.github.io/design-principles/#constructors)

**Comment by wchao1115** [comment]
Thanks @dontcallmedom for the background on the Web Platform design guidelines.

According to the section concerning the [usage of constructor](https://w3ctag.github.io/design-principles/#constructors). It claims:

> This won’t be appropriate in all cases. For example:
> - Some objects represent access to privileged resources, so they need to be constructed by factory methods which can access those resources.

In our case, I could imagine an implementation of the `ModelBuilder` construction needing access to the underlying device encapsulated by but not publicly exposed through the `NeuralNetworkContext` interface, and so, `context.CreateModelBuilder()` would be a more flexible contract for the implementer. Hope I clarify enough of my concern on this topic.

@cynthia

**Comment by wchao1115** [comment]
It appears that it should be safe for the implementer of webnn to internally cast the context type down to the underlying device. This addresses my concern of using factory method. We can use the webidl interface ctor to achieve the same goal. The PR #149 addresses this feedback.
