### ISSUE TITLE
BatchNormalization should be an optional operation

### ISSUE THREAD

**Issue by pyu10055** [webmachinelearning/webnn#187]
BatchNormalization usually are optimized away for inference (fused into conv2d op filter and bias), for example TFLite does not have this op, for compatibility purpose we shall move this op to optional section of the spec.

**Comment by wchao1115** [comment]
BatchNorm is actually fully supported as a native operation in DirectML. It is true that for performance benefit it is often fused with the preceding convolution and following `relu` activation. However, those are framework choices to make. The WebNN implementer can also choose apply that same fusion at the backend through the graph compilation step. But again, it is a requirement that this fusion be made. A backend implementation should be allowed to treat BatchNorm as a standalone operation, or fuse it with just the following relu, etc. I think it's still an implementation choice.

**Comment by pyu10055** [comment]
Thanks, Chai. Given that TF Lite does not have this op, would it be ok to mark it as optional in the spec? It's fine if the DirectML implementation includes it by default. It would be nice if the spec focuses first on what's common to all the major ML frameworks.

**Comment by wchao1115** [comment]
For the implementation that lacks native support for this operation, it can be entirely implemented by compositing other operations as illustrated in the note section of  the [batchNormalization](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-batchnorm) operation spec. I don't think we can define any of the supported operations as optional because it'll break the user's expectation.
