### ISSUE TITLE
Use modern WebIDL and Infra standard conventions

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#210]
| ℹ️ **This is a meta issue. See [the (living) task list](https://github.com/webmachinelearning/webnn/issues/210#issuecomment-1326361748) for pointers to specific issues and PRs.**
| --- |

The WebIDL spec recommends algorithmic method steps for defining operations: https://heycam.github.io/webidl/#method-steps

This spec currently uses a WebGPU spec inspired convention that differs from this best practice. We should consider adopting the "method steps" convention.

(Here's one example of method steps in context of the WebNN API spec:
https://webmachinelearning.github.io/webnn/#dom-ml-createcontext)

**Comment by anssiko** [comment]
I labeled this issue with "cr" implying we should address this issue before our Candidate Recommendation publication to satisfy "The document is considered complete and fit for purpose" requirement.

**Comment by anssiko** [comment]
Updated patterns for defining getters, setters, methods and constructors:

https://webidl.spec.whatwg.org/#getter-steps
https://webidl.spec.whatwg.org/#setter-steps
https://webidl.spec.whatwg.org/#method-steps
https://webidl.spec.whatwg.org/#constructor-steps

**Comment by anssiko** [comment]
(API review questions that'll also inform this work on method steps discussed in https://github.com/webmachinelearning/webnn/issues/298)

**Comment by anssiko** [comment]
(Renamed the issue to better reflect the scope of this work.)

@zolkis can you document here the spec sections where we need to do editorial work such as add algorithmic method steps, add internal slots, use getters, setters, define methods and constructors using the modern WebIDL conventions?

This would help the WG understand the scope of this effort and areas where contributions are welcome. I would focus this task on editorial changes and only propose normative changes when they are needed to fix a spec bug, or to clarify an aspect where the spec and implementation disagree.

The list can take a simple form of:

- [ ] Add methods step for [`createContextSync`](https://www.w3.org/TR/webnn/#dom-ml-createcontextsync)
- [ ] ...

If you feel it is easier to create a new issue for each task instead, feel free to do so.

**Comment by zolkis** [comment]
This issue is good aggregate tracker. Issues might be spanned on need, if the discussion is expected to be contained, or too big.

**Comment by zolkis** [comment]
I have been developing the features from the [TODO](https://github.com/webmachinelearning/webnn/issues/210#issuecomment-1326361748) in separate private branches in my fork. Some of them were published in PRs (some merged, some open). Most of them are still in private branches in my local repo. I will push them to my fork (without making PRs) so they become visible.

I was asked to present all upcoming changes in one fork/branch, so that all changes could be reviewed with the full context.
**The tip of my integration branch, containing all changes from the TODO [above](https://github.com/webmachinelearning/webnn/issues/210#issuecomment-1326361748), is now visible on https://zolkis.github.io/webnn/** 
(index.bs and index.html are being kept up to date, rebased from _main_ and including any upcoming fixes to my changes).
The changes from the current open PRs (clamp, concat, batch norm, sync-async execution, input fix) have been included.

@huningxin : the improved steps that we worked out in the [clamp PR](#348) (explicit steps to create platform objects for operands and activations) has been included. Should we next update the rest of the algorithms based on that?

@wchao1115 you can take a look on the current state, and if you have any feedback, it would be good to fix and include those as early as possible (so far you had feedback on types used in internal slots, not using note style for argument descriptions and remove styling from titles). I have fixed the latter two.

On how to make feedback: either in one or more issues, or I could make PRs to an upstream integration branch to be made for this purpose (e.g. _zolkis-algorithms-integration_ or any other _preferred_ name in the upstream repo) from which we could rebase/PR to _main_ when the time comes. Could someone with access rights create that target integration branch?

**Comment by wchao1115** [comment]
Thanks @zolkis. Can you please remove your current set of related PRs in the mainline PR queue, now that you have the entire change hosted in your fork? 

With the expectation that the change in this fork will be scoped to 
1. A global doc style change, and 
2. Additional implementation sections as required by the convention,

the reviewers will review the entire change in the fork and once approved, merge it all at once when it's all ready to go. Any additional change after the merge is expected to be minimal and scoped to adjusting to the set of changes previously merged. Your private fork should therefore no longer be needed once the merge happens.

This request was made with the intention to provide the reviewers with enough context behind the whole change, which will unavoidably affect the entire spec as a whole and not incremental in nature. 

The reviewers expect this entire change to be atomic, meaning that it will leave no follow-up action items after it is merged to the main content. It is important to remember that the change in this private fork is strictly scoped to the two types of changes noted above in order to avoid having a separate parallel content that is in the unmergeable state to the mainline content.

**Comment by zolkis** [comment]
@wchao1115: affected PRs will be closed when the alternative will have been set up. Right now it's not yet finished setting up.

> the reviewers will review the entire change in the fork

How exactly these changes are proposed to be reviewed? 
Reviews need PRs. 
PRs need a target branch, which (if not the _main_ branch) is currently missing. I don't have access rights to make it. I guess @anssiko can make it.

IMO the most practical way to review and integrate these changes, without affecting the _main_ branch, is using normal github practices, as follows:
- create an integration branch in this (upstream) repo
- I will make PRs to that branch from my fork (and redirect the related, currently open PRs there, after which they will be closed on the _main_ branch). With all PRs, the full set of changes are always visible at https://zolkis.github.io/webnn/  , solving the problem of viewing the whole context. 
- There can be also a single big PR with multi-thousand lines of changes, which is very impractical to review (imagine hundreds or thousands of comments in the PR) and is not really a recommended github practice.
- These PRs can be merged to the integration branch one by one.
- Optionally, issues can be created that refer to that integration branch and can have their own label.
- When all changes will be done and approved, then a single PR can be made to the _main_ branch, so the whole change set is integrated "atomically".
This would be simple and flexible, would solve the concerns, remain practical for reviewing, while following github regular practices.

About the content of the changes: bear in mind that these are actually adding algorithms, i.e. normative part of the spec. It might result in effects on the current text (so far not much, only arguments descriptions have been moved). Stylistic changes come as needed, like adding new (sub)sections and titles, collapsible algorithm blocks, visual framing of certain blocks (internal slots, validation, algorithms, etc.) IIRC no other changes were needed, and the existing changes fit pretty well in your requested policies. Any further, deeper changes can be done later via issues and PRs in the _main_ branch (regular spec work).

**Comment by anssiko** [comment]
The `zk-conventions-integration` integration branch is now ready for review.

These changes align the entire specification with modern specification conventions and add stylistic improvements on top that make navigating this specification more delightful experience.

The following resources are made available to the group to assist in this review task:

- [Preview](https://zolkis.github.io/webnn/) of `zk-conventions-integration`
- [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwebmachinelearning.github.io%2Fwebnn%2F&doc2=https%3A%2F%2Fzolkis.github.io%2Fwebnn%2F) between `main` and `zk-conventions-integration` (note: diff is slow to load)
- [Issues addressed and PRs merged to](https://github.com/webmachinelearning/webnn/issues/210#issuecomment-1326361748) `zk-conventions-integration`
- [Commits](https://github.com/webmachinelearning/webnn/compare/main...zk-conventions-integration) ahead of `main`

Thanks @zolkis for this significant effort!

**Comment by wchao1115** [comment]
@anssiko and @zolkis, do we know the ETA to merge `zk-conventions-integration` branch to `main`? I've spent some good amount of time on the change, and as far as I can, I'm signed off on it. If there's additional change to be made, please let me know how you plan to make them, either in this staging branch, or directly targeting main as needed, and if so, by when. Thanks!

**Comment by zolkis** [comment]
@wchao1115 we agreed in the WG meeting to spend the time until the next WG meeting for proofreading, sanity check etc. Our implementation team helps in doing that, and I am making extra effort to handle all comments possible, and make issues for the larger or more complex changes to be handled later. The target is that by the next WG meeting, it will be in good enough shape to be merged, and then handle the rest soon after.

**Comment by anssiko** [comment]
@wchao1115, we expect to merge latest after our next meeting 24 Aug. We have a good momentum with reviews with an extended team pulled in to help with PR #446 review and @zolkis is focused on addressing the review comments directly in the integration branch (see [commits](https://github.com/webmachinelearning/webnn/pull/446/commits)). We open new issues for proposed changes more appropriate to be addressed after this big PR has been merged.

Thanks for your efforts in driving this to completion, everyone!

**Comment by inexorabletash** [comment]
Thanks @anssiko 

So far as I can tell, all of the topics mentioned here are either already fixed or are tracked by open issues. Here's how I'd categorize what's left:

- Label these with something like "operator-specific"
  - #449
  - #334
  - #347 
  - #452

- Label these with something like "spec quality"
  - #395
  - #450
  - #455
  - #211

- Finally, label these with something like "normative" and/or "spec completeness" and/or "discussion needed". I think this is the most important category of issues.  
  - #302
  - #303
  - #333
  - #448
  - File a new issue to track: Ensure the [programming model](https://www.w3.org/TR/webnn/#programming-model) section reads well and is up to date with the latest changes

Further labels e.g. "PR needed" "has PR", "needs WPT", "has WPT" might be useful but that can be discussed separately.

**Comment by anssiko** [comment]
@inexorabletash much thanks for the label proposals and triage.

I think we could document the proposed labels and their semantics in a .md file alongside code conventions and contrib guidelines. An idea up for grabs, PRs welcome :)

**Comment by anssiko** [comment]
Thanks everyone for your work on this WebIDL and Infra standard conventions alignment effort that has resulted in a significantly improved and more precise specification. Special thanks to @zolkis and @inexorabletash for this effort!

I opened #549 and triaged the remaining open issues referenced here. We're now ready to close this tracker 👋 

From now on standards conventions related issues can be found via this label: https://github.com/webmachinelearning/webnn/labels/conventions
