### ISSUE TITLE
Support for LocalResponseNormalization (LRN) operation

### ISSUE THREAD

**Issue by MarkGHX** [webmachinelearning/webnn#228]
Hi all, 

I'm a student intern working on GSoC 2021 project "OpenCV.js: Accelerate OpenCV.js DNN via WebNN" (opencv/opencv#20406). [Here](https://docs.google.com/document/d/18PcYuRC2UCKUpustZn3t8beDF1UNfP29ikwPLPKXFuY/edit) is the proposal. In this project, I will improve the performance of OpenCV.js DNN Module using WebNN.

Here is a brief result of the improvements:
| Model   |     OpenCV.js wasm      |  OpenCV.js wasm+simd+threads | OpenCV native default | OpenCV OpenVINO | OpenCV WebNN | OpenCV.js WebNN-polyfill | OpenCV.js WebNN-Electron |
|:----------:|:-------------:|:------:|:----------:|:---------:|:---------:|:--------:|:------------:|
| GoogleNet | 825.07ms | 51.55ms | 29.32ms | 10.35ms | 24.8ms | 69.15ms | 24.90ms |
| SqueezeNet | 462.12ms | 31.69ms | 17.4ms | 4.29ms | 4.56ms | 21.27ms | 4.07ms |

However, I found that there is a performance gap of GoogleNet between OpenCV OpenVINO and OpenCV WebNN, while this gap doesn't exist for SqueezeNet. This is mainly because LRN layer is not supported by WebNN. Thus, the GoogleNet is divided into four parts, which slows down the inference speed. After a further investigation, I found that both ONNX ([link](https://github.com/onnx/onnx/blob/master/docs/Operators.md#lrn)) and TFLite ([link](https://github.com/tensorflow/tensorflow/blob/6cdc44513847d9b92d7193646fd84ba431f0e5dc/tensorflow/lite/tools/versioning/runtime_version.cc#L134)) support LRN and both GoogleNet and AlexNet need LRN layer. Thus, I think it is useful for WebNN to support this frequently used LRN op.

**Comment by fdwr** [comment]
I prototyped localResponseNormalization [here](https://github.com/fdwr/chromium-src-webnn-dml/commit/eae6a950a438728dd8f5e822b0a99994107253a9), which worked for my limited use. Though, between the various implementations (TensorFlow, CoreML, DirectML, Caffe), there are enough little differences (kernel symmetry, which axes are used, which dimensions are windowed...) that the final WebNN form probably ought to be a more generic form taking `axes` rather than just `axis` and `windowSize` rather than a `radius`; and it warrants a table with a clear mapping to each backend.

Let me amend this comment with more justification (including known models) and backend comparisons tomorrow. ⏳

```diff
partial interface MLGraphBuilder {
  ...
  MLOperand batchNormalization(
    MLOperand input,
    MLOperand mean,
    MLOperand variance,
    optional MLBatchNormalizationOptions options = {}
  );
  MLOperand instanceNormalization(
    MLOperand input,
    optional MLInstanceNormalizationOptions options = {}
  );
  MLOperand layerNormalization(
    MLOperand input,
    optional MLLayerNormalizationOptions options = {}
  );

+ MLOperand localResponseNormalization(
+   MLOperand input,
+   optional MLLocalResponseNormalizationOptions options = {}
+ );
  ...
};
```

```diff
+dictionary MLLocalResponseNormalizationOptions{
+  unsigned long windowSize = 1;
+  [EnforceRange] unsigned long axis = 1;
+  float scale = 1.0;      // Sometimes labeled alpha.
+  float bias = 1.0;       // Sometimes labeled k
+  float exponent = 0.5;   // Sometimes labeled beta.
+};
```

**Comment by fdwr** [comment]
Excluding padding in the averaging window (includePadding = false) is the WebNN default, and that's actually the hard case. Supporting includePadding = true is easy - you just add zero padding beforehand via pad and then call averagePool. So adding `includePadding` may be _useful_ (assuming all the backends support it), but not _necesary_ for implementation.

Wanming's ONNX decomposition should work with a Pad here:

![image](https://github.com/user-attachments/assets/0c73c0f6-4bbe-4028-84c2-182548797c8e)

**Comment by huningxin** [comment]
@fdwr 

> Supporting includePadding = true though is easy - you just add zero padding beforehand via pad and then call averagePool per normal.

Great idea!

> So adding includePadding may be useful (assuming all the backends support it),

AFAIK, TFLite [`average_pool_2d `](https://www.tensorflow.org/mlir/tfl_ops#tflaverage_pool_2d_tflaveragepool2dop) doesn't support `includePadding = true`, it needs to be emulated via adding zero padding beforehand.

>  but not necessary for implementation.

Agreed, it could be handled by framework.

**Comment by a-sully** [comment]
> Agreed, it could be handled by framework.

SGTM. Let's close this issue as not planned?

**Comment by fdwr** [comment]
Using decomposition in higher layers (e.g. [ORT's WebNN EP](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/core/providers/webnn/builders/impl)) for localResponseNormalization rather than a dedicated WebNN operator due to the rarity of the operator in models and the awkward backend differences.
