### ISSUE TITLE
Create a light-weight process to guide submitting new operator requests to WebNN

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#231]
From WebML WG Teleconference – 18 Nov 2021: 

>[RESOLUTION](https://www.w3.org/2021/11/18-webmachinelearning-minutes.html#r01): Create a light-weight process to guide submitting new operator requests to WebNN

Recording this resolution as an issue so we remember to bootstrap this process.

[In our discussions](https://www.w3.org/2021/11/18-webmachinelearning-minutes.html#t02), the following ONNX guidelines were suggested to be adopted for WebNN:

- "Prefer static attributes over dynamic input values"
- "Shape inference logic should be included"

Concretely, we could implement this process as an issue/PR template.

Feel free to share best practices/guidelines here to be used as a basis for the first version.

**Comment by huningxin** [comment]
As we are starting to work on WebNN v2 features, like [transformers](https://github.com/webmachinelearning/webnn/issues/375), more new op proposals are coming. There is a demand to clarify the process and criteria for adding new ops.

Also, in WebML WG Teleconference – 13 April 2023, @wchao1115 proposed that

> Chai: I'd like us to write contribution guidelines for spec changes to help contributors.

Ideally, this issue could be fixed by the guidelines as the 4th category of contribution:

> 4) New content, add new ops, here's why with likely uber issue defining the rationale, this category is the most time consuming for the editor, need to understand the direction and keep the API consistent with the charter

/cc @fdwr @wacky6

**Comment by anssiko** [comment]
Fixed by #381 and specifically the section [Proposing and adding a new operation](https://github.com/webmachinelearning/webnn/blob/main/CONTRIBUTING.md#proposing-and-adding-a-new-operation).
