### ISSUE TITLE
Define the data type of the padding, strides and dilations of MLConv2dOptions as sequence<unsigned long>

### ISSUE THREAD

**Issue by miaobin** [webmachinelearning/webnn#269]
The data type of padding, strides and dilations of [MLConv2dOptions](https://webmachinelearning.github.io/webnn/#dictdef-mlconv2doptions) are defined as `sequence<long>` now. When we implement the backends of WebNN, we found that the data type of these arguments were defined differently by each backend. In fact, there is no need to use negative value for these three arguments, unlike `axis` in [MLSplitOptions](https://webmachinelearning.github.io/webnn/#dictdef-mlsplitoptions). So should we use `sequence<unsigned long>` to define these three arguments?

Backend | Data Type
-- | --
OpenVINO | int32
DirectML | uint32
MLAS | int64
XNNPack | uint32
OneDNN | int64
NNAPI | int32

**Comment by anssiko** [comment]
Thanks @miaobin. Unless we have a reason to believe negative values might be needed in the future, using [`unsigned long`](https://webidl.spec.whatwg.org/#idl-unsigned-long) instead of [`long`](https://webidl.spec.whatwg.org/#idl-long) type is reasonable. See also https://www.w3.org/TR/design-principles/#numeric-types that suggests preference for `(unsigned) long long`. We probably have a "specific reason" for WebNN to use `unsigned long` instead, so documenting it in the spec on the same pass might be a good idea.

@huningxin @wchao1115 for comments.

**Comment by wacky6** [comment]
During WebNN chromium code review: https://chromium-review.googlesource.com/c/chromium/src/+/3878868/comments/fc3a6110_017360f2

I wonder if negative stride / padding / dilation is ever defined? If so, what does that mean mathematically?

**Comment by huningxin** [comment]
I am not aware any specific usage of negative values for these attributes. This issue would also apply to similar attributes of `MLConvTranspose2dOptions` and `MLPool2dOptions`.

**Comment by fdwr** [comment]
> I wonder if negative stride / padding / dilation is ever defined? If so, what does that mean mathematically?

Conceptually it would mean (for negative strides and dilations) the content is flipped or cropped (for negative padding), but I've never seen this done. I have seen 0 dilations though, which essentially repeats the input value kinda like broadcasting.
