### ISSUE TITLE
OperandDescriptor's dimension should match ECMAScript's TypedArray dimension

### ISSUE THREAD

**Issue by BenjaminPoulain** [webmachinelearning/webnn#29]
In OperandDescriptor, the size of each axis is defined in "dimensions" as "long".

The limits of the "[long](https://www.w3.org/TR/WebIDL-1/#idl-long)" type do not match the length definition of [TypedArray](https://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%-length).

For consistency and to avoid bugs caused by conversion, it would be better to accept a Number in "dimensions" and use [ToLength()](http://www.ecma-international.org/ecma-262/6.0/#sec-tolength) to obtain the size.

**Comment by inexorabletash** [comment]
For those not aware of the details of the ECMAScript spec:

* Since this was filed, MLOperandDescriptor (and other places that use dimensions) are defined using [unsigned long](https://webidl.spec.whatwg.org/#idl-unsigned-long) which has the range **0 through 2<sup>32</sup>-1** (i.e. max unsigned 32 bit integer)
* ECMAScript's ToLength clamps values to the range **0 through 2<sup>53</sup>-1** (i.e. max uniquely representable integer in 64 bit floats)

**Comment by anssiko** [comment]
Thanks @inexorabletash for the status update. The WG has settled on unsigned long for dimensions and has gathered significant implementation experience. We'll revisit if new information emerges.
