### ISSUE TITLE
Handle errors according to Web IDL conventions

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#314]
When handling errors, the spec should follow the [Web IDL convention](https://webidl.spec.whatwg.org/#idl-exceptions):

> [Simple exceptions](https://webidl.spec.whatwg.org/#dfn-simple-exception) can be created by providing their [error name](https://webidl.spec.whatwg.org/#dfn-exception-error-name). A [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException) can be [created](https://webidl.spec.whatwg.org/#dfn-create-exception) by providing its [error name](https://webidl.spec.whatwg.org/#dfn-exception-error-name) followed by [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException). Exceptions can also be thrown, by providing the same details required to [create](https://webidl.spec.whatwg.org/#dfn-create-exception) one.

**Comment by anssiko** [comment]
Thanks for filing this.

We should align both the simple exceptions and DOMException usage with conventions. Here's my understanding:

[Simple exceptions](https://webidl.spec.whatwg.org/#dfn-simple-exception) are [created](https://webidl.spec.whatwg.org/#dfn-create-exception) with a "new" keyword because they're ECMAScript error types. IOW, in JS console this test should be true: `typeof new TypeError === 'object'`.

To create a new `DOMException` with [any of these names](https://webidl.spec.whatwg.org/#idl-DOMException-error-names) we don't use the "new" keyword but the "newly created" syntax:
>To create a new [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException) with [error name](https://webidl.spec.whatwg.org/#dfn-exception-error-name) "[SyntaxError](https://webidl.spec.whatwg.org/#syntaxerror)":
>Let object be a newly [created](https://webidl.spec.whatwg.org/#dfn-create-exception) "[SyntaxError](https://webidl.spec.whatwg.org/#syntaxerror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException).

Please investigate that my understanding is correct and once you're confident apply the conventions to the whole spec.

**Comment by zolkis** [comment]
The spec prose to be used, as also done in html, infra, fetch etc. specs:

1. For [simple exceptions](https://webidl.spec.whatwg.org/#dfn-simple-exception),

```throw a {{TypeError}} ```

or 

``` reject |promise| with a {{TypeError}}```

2. For [DOMExceptions](https://webidl.spec.whatwg.org/#idl-DOMException),

```throw a "{{SecurityError}}" {{DOMException}}```

or

```reject |promise| with a "{{SecurityError}}" {{DOMException}}```

**Comment by anssiko** [comment]
Thanks for checking the other specs too, that looks right to me.
