### ISSUE TITLE
Subclass MLGraph based on the context that creates it

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#344]
Split from https://github.com/webmachinelearning/webnn/issues/341#issuecomment-1429249964, where @wacky6 mentioned

> Maybe we should subclass MLGraph based on the context that creates it. For example, CPU context returns a `MLCpuGraph` with `compute()`. GPU context returns a `MLGpuGraph` with `compute()` and GPU interop methods (commandBuffer, dispatch, etc).

If we fold the command recording methods into `MLGpuGraph`, it may not support recording multiple `MLGraph`s into one command buffer that `MLCommandEncoder` supports. Pipelining models execution may reduce the GPU queue submission overhead and improve the throughput.

/cc @wchao1115

**Comment by anssiko** [comment]
I'm hearing this redesign would impact the current `MLCommandEncoder` design. I'm proposing to revisit this issue when we have received further implementation experience and user feedback for the current [MLCommandEncoder](https://www.w3.org/TR/webnn/#mlcommandencoder) interface.

Perhaps we are able to address this issue with better example code on how to use the GPU command encoder.

**Comment by a-sully** [comment]
Does subclassing `MLGraph` still provide value if `MLCommandEncoder` does not exist?

My reading of this issue is that it has so far provided the following reasons for subclassing `MLGraph`:
1. Creating an `MLCommandEncoder` from an `MLGraph` only makes sense if the `MLGraph` will execute on GPU (and the GPU) 
2. You may call `compute()` if the `MLGraph` will execute on CPU, or `dispatch()` if the `MLGraph` will execute on GPU
 
With regards to (1), the `MLCommandEncoder` proposal is no longer being pursued (https://github.com/webmachinelearning/webnn/issues/528). This is no longer relevant

With regards to (2), I see a few problems to this. IMHO it would be nice to have one method to perform "execute the graph", but I'll leave that discussion for another issue. Given that the (very tentative, mind you) [`MLBuffer` ](https://github.com/webmachinelearning/webnn/issues/482) proposal puts the `dispatch()` method on the `MLContext` rather than the `MLGraph`, it seems that even if we do have multiple methods to perform "execute the graph", subclassing is likely not necessary

---

Are there other reasons to want this subclassing? If not, I would like to advocate for closing this issue :)

**Comment by inexorabletash** [comment]
+1 to closing

**Comment by zolkis** [comment]
> IMHO it would be nice to have one method to perform "execute the graph", regardless of the backend

+1 for that.

**Comment by huningxin** [comment]
+1 to closing this issue.
