### ISSUE TITLE
`split` into sizes are not widely supported

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#392]
This issue was raised by @wacky6 in [Chromium CL](https://chromium-review.googlesource.com/c/chromium/src/+/4420165/comment/15894d35_cf6cabf8/) review. Thanks Jiewei again!

WebNN [`split`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-split) supports two variants, "number of split" (when `splits` argument is an `unsigned long`) or "split into sizes" (when `splits` argument is a `sequence<unsigned long>`). 

When implementing this op, we observed that there are some backends don't support "split into sizes" variant, e.g. XNNPACK. For this case, we may follow the sample code that decomposes the `split` into multiple `slice`s. Or just throw error and leave to framework to handle. There are tradeoffs, we'd like to get WG's inputs on:

> If some backend doesn't offer the split implementation permitted in the spec, either 1) throw error, or 2) polyfill.
> 1) doesn't look attractive since it can't be feature detected before building the graph. This also means split op isn't interoperable (because it depends on the underlying platform)
> 2) implementation complexity (we need to bite the overhead if we slice())

**Comment by fdwr** [comment]
Although having a `split` in WebNN is not *strictly* necessary (because it can always be decomposed into multiple `slice` calls), it *is* rather common, as the following support variable length splits:

- https://www.tensorflow.org/api_docs/python/tf/split
- https://pytorch.org/docs/stable/generated/torch.split.html
- https://onnx.ai/onnx/operators/onnx__Split.html

## Options:

1. *Backend decomposes variable lengths into slice calls* - the backend can do this more efficiently than each individual calling library would achieve by repeating the logic, and it leaves room for the backend to support an optimized form later.
2. *Front end decomposes variable lengths into slice calls* - the caller *can* loop with slice calls, but it's suboptimal as perf opportunities may be lost (like in-place execution with zero copies).
3. *Throw error and leave to framework to handle* - worst option imo, because it's quite awkward for the caller. For clients like the ORT WebNN EP, it would be challenging to encounter such an error and then unwind and regenerate the graph again by manually splitting a split into multiple WebNN slice calls. I generally see that a CPU backend should be the most complete, because failed GPU execution can fallback to the CPU, but failed CPU execution can't necessarily fall back to a GPU (there may not even be a GPU capable of compute on some machines).

**Comment by fdwr** [comment]
> some backends don't support "split into sizes" variant

🤔 What about splits' opposite function, [concat](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-concat), as Concat and Split form a symmetric pair? Does XNNPack not support variable size concat either?

**Comment by a-sully** [comment]
FWIW [the XNNPACK backend has since been removed from Chromium](https://crrev.com/c/5532639). All of the remaining backends currently being explored - [CoreML](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.tensor_operation.split), [DML](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_split_operator_desc), and [TFLite](https://www.tensorflow.org/mlir/tfl_ops#operands_130) - support variable-sized split-by-size

Since any future backend we may want to implement WebNN on top of can emulate variable-sized splits if necessary, I say we close this issue. Thoughts?

**Comment by fdwr** [comment]
> All of the remaining backends currently being explored - [CoreML](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.tensor_operation.split), [DML](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_split_operator_desc), and [TFLite](https://www.tensorflow.org/mlir/tfl_ops#operands_130) - support variable-sized split-by-size

Great - vote to close then.

**Comment by huningxin** [comment]
Closing, thanks for the update!
