### ISSUE TITLE
Facial Landmark Detection for spatial computing

### ISSUE THREAD

**Issue by munrocket** [webmachinelearning/webnn#473]
Is it possible to get facial landmarks without compromising privacy with webnn?
It can be useful feature for immersive 3d content in browsers on laptops/mobiles with parallax effect.

**Comment by anssiko** [comment]
Thanks for your interest. We have made available a suite of [WebNN Samples](https://webmachinelearning.github.io/webnn-samples-intro/) that showcase selected web experiences enabled by WebNN. Facial Landmark Detection is one of them.

One of the many benefits of the WebNN API is that it's privacy preserving by design: camera feed used as input does not have to leave your device and all compute can happen locally on your device.

I hope this answers your question.

Please note this repository is focused on technical discussion regarding the WebNN API specification development. If you have questions regarding the WebNN Samples, the [webnn-samples](https://github.com/webmachinelearning/webnn-samples) repo is a more appropriate place to ask follow-up questions. If you want to propose WebNN API changes to better integrate with the WebXR Device API (or other Web APIs), those discussions are appropriate for this webnn repository.
