### ISSUE TITLE
Remove `builder.constant(value, type)` variant

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#475]
In the current spec, [`MLGraphBuilder.constant(value, type)`](https://www.w3.org/TR/webnn/#dom-mlgraphbuilder-constant-value-type) allows to build a scalar from the specified number, e.g.,
```js
const a = graphBuilder.constant(42.0, 'float32');
```

However, [`MLGraphBuilder.constant(descriptor, bufferView)`](https://www.w3.org/TR/webnn/#dom-mlgraphbuilder-constant) also allows to build a scalar from data buffer, like the example in #390

```js
const b = graphBuilder.constant({type: 'float32'}, new Float32Array([42.0]));
```

The proposal is to drop the scalar-specific `MLGraphBuilder.constant(value, type)` method and only keep more generic `MLGraphBuilder.constant(descriptor, bufferView)` method. 

The scalar-specific build method can be polyfilled by user code. This would help reduce the browser implementation complexity.

/cc @wchao1115 @fdwr @wacky6 @BruceDai @Honry 

(Edit by @anssiko: fix link and naming to account for name changes dataType -> type and buffer -> bufferView)

**Comment by wacky6** [comment]
sgtm :)

**Comment by fdwr** [comment]
It's certainly more convenient to have the constant scalar overload, but I suppose if we don't expect ordinary JS users to call WebNN directly (more of a framework backend), it doesn't matter much. I also suppose there is no perf benefit to it either, because under the hood, that constant becomes a buffer anyway. One useability data point is that I just scanned my *own* SimpleWebNN.html test file (~3000 lines long), and I found 0 occurrences of the `constant` scalar overload. Even the cases where I specified only a single value, I still used the full form 🤔:

    const constant = graphBuilder.constant(constantDesc, new Float32Array([44.0]));

So, I guess the biggest impact of this change codewise would be our hello world samples :b.

I don't oppose it.

(random aside) Huh, I never noticed these two overloads have swapped parameters. For one overload, you specify the value in parameter 1 (e.g. 42) and the type (e.g. "float32") in parameter 2, but for the other overload, you specify the type in parameter 1 and pass the value in parameter two. 🤔 Having consistent ordering between them would be nice. I suppose the reasoning was that you could just specify the constant, defaulting the type as an optional parameter to `float32`.

**Comment by inexorabletash** [comment]
Given discussions in #492 about rethinking constant() overloads in general... how are people feeling about this issue? Proceed with removal? Retain but change the signature? Other?

I note that many of the decompositions given in the spec use this, e.g. `builder.constant(0)`, `builder.constant(options.alpha)`, etc. Updating those to take a required dataType is doable, e.g. for relu()

```diff
-return builder.max(builder.constant(0), x);
+return builder.max(builder.constant(x.dataType, 0), x);
```
... but it gets uglier if the overload is removed entirely.

**Comment by fdwr** [comment]
I'm warming to keeping the scalar constant overload for convenience and to benefit for decompositions in the spec, but passing the parameters in the order `(MLOperandDataType, MLNumber)` would be more self consistent.

The `relu` decomposition example is definitely a typo, because that [const overload](https://www.w3.org/TR/webnn/#dom-mlgraphbuilder-constant-value-type) needs a data type. @huningxin?
