### ISSUE TITLE
Clarify the expected behavior for `axes` being empty `[]`

### ISSUE THREAD

**Issue by BruceDai** [webmachinelearning/webnn#493]
Current Spec isn't clear for `axes` being empty `[]` for below operations.

op|
|---|
argMin/Max|
layerNormalization|
Reduction operations|
resample2d|

@fdwr explained this `axes=[]` for **argMin/Max** when his reviewing on [my baseline implementation](https://github.com/webmachinelearning/webnn-baseline/pull/62) like [the comment](https://github.com/webmachinelearning/webnn-baseline/pull/62#discussion_r1427551113) and also kindly demoed [the test cases of axes=[]](https://github.com/webmachinelearning/webnn-baseline/pull/62#discussion_r1427564488) (Thanks @fdwr! )

> If you pass axes = [], will that correctly use the explicit empty axes (output shape is then the same size as the input, and there is a 1:1 mapping of output indices) rather than generate full reduction?

> ![image](https://github.com/webmachinelearning/webnn/assets/1531742/183fddbc-79b2-443c-bd6b-02a60d543f0d)
> ![image](https://github.com/webmachinelearning/webnn/assets/1531742/088422f6-15f2-44ef-b723-ab34ec86b097)

**Comment by fdwr** [comment]
Yeah, the spec could be clearer here because it's not obvious. When the `axes` are explicitly defined to `axis: []` for an op like `reduceSum` (so not *undefined*, and thus not global reduction), then I expect them to behave 1:1 where output size matches input size, consistent with libraries like TF and ONNX which WebNN underpins.

Similarly, `layerNormalization` and `argMin`/`argMax` should have well-formed output in such cases. Algorithmically, there is no ambiguity, and I *believe* the Chromium implementation actually already does the right thing (need to double check...) in these cases from the unit tests I recall seeing.

For `resample2d`, axes are not allowed to be `[]` anyway (only 2 axis values).

```
import tensorflow as tf
x = tf.constant([[0,100],[200,300]], dtype=tf.float32)
y = tf.math.reduce_sum(x, axis=[])    # https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum
print("value:", y)
print("shape:", y.shape)

# Prints:
# value: tf.Tensor(
# [[  0. 100.]
#  [200. 300.]], shape=(2, 2), dtype=float32)
# shape: (2, 2)
```
