### ISSUE TITLE
Standardize on × or * for multiplication, and ÷ or / for division in formulas

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#506]
Total nitpick, but:

* × is currently used in two places in the spec, * seems to be used in about 43 places.
* ÷ is currently used in one place in the spec, / seems to be used in about 10 places. 

... not counting code examples.

Personally I find × and ÷ less ambiguous in spec formulas, but the important thing is to be consistent.

**Comment by inexorabletash** [comment]
I also noticed two instances of ∗ (U+2217 Asterisk Operator) for multiplication!

**Comment by fdwr** [comment]
Yeah, for the *code snippets* (e.g. `builder.slice(options.bias, [2 * hiddenSize], [hiddenSize])`), it makes sense to use the typical `*` and `/` (typical in programming anyway, and more of our readers will be coders moreso than mathematicians).

For the documentation *prose* (e.g. `Let elementsNumber be the result of view’s byte length ÷ view’s element size.`), I don't care as much (people can probably read either fine), but consistency across the prose and code snippets is consideration too ⚖. Personally as an implementor of multiple specs in the past, the less friction that exists between the spec and the code I needed to implement, the happier I was (e.g. prefering simple linear notation for formulas and readable operand names like `sum(x * scale) + bias` rather than terse and less transferrable legacy notation `(𝝨 x × σ) + β)`).

> Personally I find × and ÷ less ambiguous in spec formulas

Though yeah, I recognize that in specifications which use more math operations besides just the Hadamard product (∘∗⊗⊙⊛⊚...) that `×` might be clearer than `*`. Happy to hear other inputs too...
