### ISSUE TITLE
Need clarify scale factor for resample2d 

### ISSUE THREAD

**Issue by BruceDai** [webmachinelearning/webnn#610]
Link to **resample2d** definitions: https://webmachinelearning.github.io/webnn/#mlgraphbuilder-calculate-resample-output-sizes.

1) The **output sizes** by calculating with **scales** are not correct, and the `desc's shape` is not accurate since the **shape** is defined as "An MLOperand's shape is its [[descriptor]].dimensions.". - I submitted a pr #611 to fix it, please take a review, thanks.

2) And it needs clarify the limitations for the product of scale factor and spatial dimension's size, I write such tests in my [CL-5382118](https://chromium-review.googlesource.com/c/chromium/src/+/5382118/1/third_party/blink/web_tests/external/wpt/webnn/validation_tests/resample2d.https.any.js), please take a look, thanks.

**Comment by inexorabletash** [comment]
Re: overflow - see https://github.com/webmachinelearning/webnn/pull/582#discussion_r1503641101 for some discussion

**Comment by huningxin** [comment]
The ["check resample options" step](https://www.w3.org/TR/webnn/#mlgraphbuilder-check-resample-options) check the scale value should be positive:

> If options.scales does not exist, set it to the list « 1.0, 1.0 ».
> Otherwise, if any of its values is not greater than 0, or if its size is not 2, return false.

**Comment by inexorabletash** [comment]
Side observation: the Chromium code has `if (scales[0] < 0 || scales[1] < 0)` - it seems like those tests should be `<=` instead

https://source.chromium.org/chromium/chromium/src/+/main:components/ml/webnn/graph_validation_utils.cc;l=1024

**Comment by huningxin** [comment]
> Side observation: the Chromium code has `if (scales[0] < 0 || scales[1] < 0)` - it seems like those tests should be `<=` instead

+1

> https://source.chromium.org/chromium/chromium/src/+/main:components/ml/webnn/graph_validation_utils.cc;l=1024

@mingmingtasd, could you please take a look at the chromium impl?

**Comment by mingmingtasd** [comment]
> Side observation: the Chromium code has `if (scales[0] < 0 || scales[1] < 0)` - it seems like those tests should be `<=` instead
> 
> https://source.chromium.org/chromium/chromium/src/+/main:components/ml/webnn/graph_validation_utils.cc;l=1024

Thanks! Good catch! I open: https://issues.chromium.org/issues/332587370 to track, and will fix that.

**Comment by inexorabletash** [comment]
Re: _clarify the limitations for the product of scale factor and spatial dimension's size_

I filed #636 for the general issue. One thing I'm not clear on reading the code (https://source.chromium.org/chromium/chromium/src/+/main:components/ml/webnn/graph_validation_utils.cc;l=974 I think) is: is this just an implementation imposed limit because the Chromium implementation happens to use uint32_t internally?

* If it's just an implementation-imposed limit, I think we should just reference #636 and close this issue
* Otherwise, we should add something to the spec specific to resample2d

**Comment by huningxin** [comment]
@inexorabletash 

> One thing I'm not clear on reading the code (https://source.chromium.org/chromium/chromium/src/+/main:components/ml/webnn/graph_validation_utils.cc;l=974 I think) is: is this just an implementation imposed limit because the Chromium implementation happens to use uint32_t internally?

I suppose this is not an implementation imposed limit. According to [calculate resample output sizes](https://www.w3.org/TR/webnn/#mlgraphbuilder-calculate-resample-output-sizes) step

> Otherwise, set desc.[dimensions](https://www.w3.org/TR/webnn/#dom-mloperanddescriptor-dimensions)[options.[axes](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-axes)[index]] to floor(input’s [shape](https://www.w3.org/TR/webnn/#mloperand-shape)[options.[axes](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-axes)[index]] * options.[scales](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-scales)[index]).

Because desc.[dimensions](https://www.w3.org/TR/webnn/#dom-mloperanddescriptor-dimensions)[options.[axes](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-axes)[index]] is of type uint32, if the result of floor(input’s [shape](https://www.w3.org/TR/webnn/#mloperand-shape)[options.[axes](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-axes)[index]] * options.[scales](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-scales)[index]) is out of range of uint32, it should throw a TypeError. I guess the value 0 limit is due to WebNN doesn't allow 0 size dimension that is being discussed at https://github.com/webmachinelearning/webnn/issues/391.

**Comment by inexorabletash** [comment]
> Because desc.[dimensions](https://www.w3.org/TR/webnn/#dom-mloperanddescriptor-dimensions)[options.[axes](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-axes)[index]] is of type uint32, if the result of floor(input’s [shape](https://www.w3.org/TR/webnn/#mloperand-shape)[options.[axes](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-axes)[index]] * options.[scales](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-scales)[index]) is out of range of uint32, it should throw a TypeError.

Heh, thanks for reading the spec for me. :) So we should spec that. I'll put up a PR.
