### ISSUE TITLE
Need clarify the usage of axes=[0,1] for resample2d

### ISSUE THREAD

**Issue by BruceDai** [webmachinelearning/webnn#624]
This issue was raised as @fdwr's below [comment](https://chromium-review.googlesource.com/c/chromium/src/+/5382118/comment/57f65e31_76bf34f6/) for reviewing Chromium [CL-5382118](https://chromium-review.googlesource.com/c/chromium/src/+/5382118). 

> `axes=[0,1]` is an odd one, and I wonder the history behind it (decided before I joined). Some other ML libraries simply treat axes as numbers (no associated semantics to any particular dimensions), but WebNN limits them to `[0,1]`, `[1,2]`, `[2,3]`; and while the `axes=[1,2]` and `axes=[2,3]` uses are obvious (for NHWC and NCHW tensors respectively), the `[0,1]` scenario makes me go hmm, because if the semantic interpretation of the input tensor is **NH**WC, then it would mean resampling the batch and height (but not the width 🙃), which wouldn't make any sense; whereas if the semantic layout of the input was **NC**HW, then it would mean simultaneously resampling the batch dimension (useful for replication) and expanding the channel count, which *can* make sense. However, if resampling NC in **NC**HW is useful, then resampling NC in **N**HW**C** should be deemed useful too, but `axes=[0,3]` is currently disallowed by the spec. 🤔

/cc @fdwr @huningxin @a-sully, PTAL, thanks.

**Comment by inexorabletash** [comment]
Maybe asking the same question in a different way:

If [`resample2d()`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-resample2d-method) is only for use with tensors of NHWC and NCHW layouts, then should it take an [`MLInputOperandLayout`](https://www.w3.org/TR/webnn/#enumdef-mlinputoperandlayout) param instead of an [`axes`](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-axes) param? 

If not, what are the other use cases, and how can we support them via [`axes`](https://www.w3.org/TR/webnn/#dom-mlresample2doptions-axes)?

**Comment by inexorabletash** [comment]
I guess [0,1] makes sense if you're just dealing directly with 2D data. But you could do a trivial reshape() to NHWC or NCHW with N=1 C=1 and back if needed.

**Comment by philloooo** [comment]
Signal boosting this one.  Changing to take [MLInputOperandLayout](https://www.w3.org/TR/webnn/#enumdef-mlinputoperandlayout) seems to make sense to me? 

Note both tflite and coreml only do the resample to spacial dimensions, and they both only support one layout, so it would be similar to conv2d that we will insert transposes for the other layout.

**Comment by philloooo** [comment]
gentle ping @fdwr @huningxin

**Comment by huningxin** [comment]
I am not aware of any use cases of using axes [0, 1]. 

Actually, in my initial [PR](https://github.com/webmachinelearning/webnn/pull/205), I proposed resample2d taking input operand layout and only interpolating spatial dimensions. Please see discussion: https://github.com/webmachinelearning/webnn/pull/205#discussion_r701495238. The main reason to support axes was from framework perspective, like ONNX. Now when we revisit this issue from platform API implementability angle, given both tflite and coreml only interpolate spatial dimensions, we probably should revert and start with the intersection.

**Comment by fdwr** [comment]
Resampling is *usually* useful for spatial dimensions, but not limited to them - you could resample across channels (feature maps) too (`axes = [1]`).

(the contrarian arrives...) 🤔 The longer I've worked in ML, and the more API differences I come across, the more allergic I've become to *implicitly* assigning arbitrary semantics to axis numbers rather than *explicitly* passing the axes you want to work with. The notion of layout is also a costly bug farm, and it complicates composition of operators. So if anything, I'd really like to *eliminate* more occurrences of "layout" within WebNN rather than *introduce* more 😢. Using axes is elegant here, and I was more pointing the inconsistency why only *certain* patterns were supported rather than just treating it generically. Every combination ([0,3], [2,1], [1,2], [1,3]...) is trivially implementable via a bracketing transpose (see pseudocode below).

> The main reason to support axes was from framework perspective, like ONNX.

Indeed, supporting ORT's WebNN EP as a caller still matters, for which `Resize` comes as `axes`. TF and CoreML can both implement them without challenge, using the optimal path when `axes` is directly compatible, and the transposed path when not:

## CoreML

```
if axes == [2,3]
    return image_resizing.resample(input, ...)
else
    permutation = getPermutationToRightmostDimensions(input.rank, axes)
    x = tensor_transformation.transpose(input, permutation)
    y = image_resizing.resample(x, ...)
    z = tensor_transformation.transpose(y, getInversePermutation(permutation))
endif

// Where getPermutationToRightmostDimensions(...) is a little helper that returns a permutation vector
// such that the given axes are aligned to the right edge. So input rank = 4 with axes = [1,2] yields [0,3,1,2].
```

## TensorFlow

```
if axes == [1,2]
    return tf.image.resize(input, ...)
else
    permutation = getPermutationToRightmostDimensions(input.rank, axes)
    x = tf.transpose(input, perm=permutation)
    y = tf.image.resize(x, ...)
    z = tf.transpose(y, perm = getInversePermutation(permutation))
endif
```

Technically 1D resampling (e.g. axes = [1]) is a subset of 2D, implementable by just prepending a 1 to the scale factor for the 2nd dimension. Even 3D resampling (e.g. axes [1,2,3]) is even achievable with a 2D backend via 2 calls, calling resample once along axes [2,3] and again on axis [1] - it's not pretty, but it's not difficult.
