### ISSUE TITLE
Shall we update the spec to add constraints on the axes and the input rank for the reduction operator?

### ISSUE THREAD

**Issue by mei1127** [webmachinelearning/webnn#681]
(This was raised by @a-sully  in Chromium [CL-5496412](https://chromium-review.googlesource.com/c/chromium/src/+/5496312/) review.)

For WebNN's [reduction](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-reduce) operator:
Austion proposed to update the spec to add constraints on the axes and the input rank.

> [The Chromium code which validates reductions](https://crsrc.org/c/components/ml/webnn/graph_validation_utils.cc;l=1953-1973;drc=64d81c6bd0aa2132c451b8a0e861e56d1ce3a221;bpv=0;bpt=1) also fails if
> [the input rank is zero](https://crsrc.org/c/components/ml/webnn/graph_validation_utils.cc;l=243-246;drc=64d81c6bd0aa2132c451b8a0e861e56d1ce3a221)
> [values in axes are duplicated](https://crsrc.org/c/components/ml/webnn/graph_validation_utils.cc;l=2060-2063;drc=64d81c6bd0aa2132c451b8a0e861e56d1ce3a221)
> Shall we update the spec and add WPTs accordingly?

/cc @a-sully

**Comment by inexorabletash** [comment]
Makes sense to me - I put up a PR

**Comment by fdwr** [comment]
(repeating here too) 
Nop reductions are valid (where `axes` are empty), and scalars are just another instance of a nop:

```python
x = tensorflow.constant([3,3,3], dtype=tensorflow.float32)
y = tensorflow.reduce_sum(x, axis=[])

# value: tf.Tensor([3. 3. 3.], shape=(3,), dtype=float32)
# shape: (3,)

x = tensorflow.constant([], dtype=tensorflow.float32)
y = tensorflow.reduce_sum(x, axis=[])

# value: tf.Tensor([], shape=(0,), dtype=float32)
# shape: (0,)
```

What's *not* valid is a scalar reduction with *non-empty* axes, because that would index axes beyond the rank, but the existing check that each axis < inputRank already validates that condition, and so checking input rank is redundant and unnecessarily exclusionary. So, we should remove [that line](https://source.chromium.org/chromium/chromium/src/+/main:components/ml/webnn/graph_validation_utils.cc;l=243-246;drc=64d81c6bd0aa2132c451b8a0e861e56d1ce3a221) in Chromium.

```suggestion
```

**Comment by inexorabletash** [comment]
Groovy. I have a Chromium CL (with WPT changes) up to remove the rank check crrev.com/c/5529350 but I'm a bit rusty so it may not land for a bit.

**Comment by fdwr** [comment]
> chromium-wpt-export-bot pushed a commit to web-platform-tests/wpt

Oh interesting. So making the change in Chromium land actually pushes it *back* into `web-platform-tests/wpt`.

**Comment by inexorabletash** [comment]
Yeah, we have two-way sync set up with WPT. Mozilla and Apple have something similar. It's not perfect and requires some babysitting, but it's super great when it works.
