### ISSUE TITLE
Use USVString for operand name

### ISSUE THREAD

**Issue by philloooo** [webmachinelearning/webnn#713]
I was reviewing the [label implementation](https://chromium-review.googlesource.com/c/chromium/src/+/5528797) and realized the WebGPU uses [USVString for label](https://www.w3.org/TR/webgpu/#dom-gpuobjectbase-label) ([see previous discussion](https://github.com/gpuweb/gpuweb/issues/784)).

I think we should use USVString for [MLOperand](https://www.w3.org/TR/webnn/#api-mloperand) name too? Chromium implementation currently utf-8 encode the name and send it to backends, and the names are further serialized to backend specific representations([coreml](https://source.chromium.org/chromium/chromium/src/+/main:services/webnn/coreml/graph_builder_coreml.cc;l=2633;bpv=1;bpt=1?q=graph_builder_coreml.cc), [tflite](https://source.chromium.org/chromium/chromium/src/+/main:services/webnn/tflite/graph_builder_tflite.cc;l=288?q=graph_builder_tflite.cc)).

**Comment by inexorabletash** [comment]
To make the problem more concrete: if specified as a DOMString and something like "blah\uD800" is passed, since that has an unpaired UTF-16 surrogate there's no standard way to interpret that as a sequence of Unicode code points, so if back-ends treat it as anything but an opaque sequence of 16-bit code units, then there's a risk of interop issues - the label might come back out from errors as "blah\uD800" or "blah\uFFFD" or "blah\xED\xA0\x80" or ... 

Using USVString enforces standard behavior when a string like that is passed - it becomes "blah\uFFFD" which can be transcoded to UTF-8. 

The down sides are that if code were to intentionally try to use "blah\uD800" as a name or label then they wouldn't get what they expected coming out - but as noted, that's already a problem if back-ends do anything with the strings. And if code passed both "blah\uD800" and "blah\uD801" they are both corrected to "blah\uFFFD"  so would collide as keys. But again, depending on what back-ends do, that may already be a problem.

**Comment by fdwr** [comment]
Ah, so [USVString](https://docs.w3cub.com/dom/usvstring.html), [DOMString](https://docs.w3cub.com/dom/domstring), and JavaScript [String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) are all just different names of the identical underlying encoding, UTF-16. It's just that USVString is a string which guarantees no unpaired surrogates (any occurrences have been replaced with � U+FFFD).

> WebGPU uses [USVString for label](https://www.w3.org/TR/webgpu/#dom-gpuobjectbase-label)

I like the consistency aspect with WebGPU's existing label.

> The down sides are that if code were to intentionally try to use "blah\uD800" as a name or label then they wouldn't get what they expected coming out

🤔 I'm really not concerned with such degenerate cases 🐞, because where would the ill-formed sequence come from in the first place? If these names are coming from model files, then I expect they're well-formed to begin with (e.g. in ONNX ["All strings are encoded in UTF-8"](https://onnx.ai/onnx/repo-docs/IR.html), and SafeTensors ["a JSON UTF-8 string representing the header"](https://github.com/huggingface/safetensors)). Of course, one could call WebNN directly, but using unpaired surrogates like that would be a brittle abuse.* Additionally Python builds apparently come in flavors of UCS-2 (which lack surrogate pair code units anyway) or UCS-4 (which shouldn't have surrogate pairs either).
