### ISSUE TITLE
Restrict dimensions size to [0, INT32_MAX]

### ISSUE THREAD

**Issue by philloooo** [webmachinelearning/webnn#734]
Currently we use uint32 for dimensions, so the range is [0, UINT32_MAX]. 

Both CoreML and tflite backends actually use int32_t for dimensions, so the range can't exceed `INT32_MAX`, meaning if we pass dimensions that's between INT32_MAX and UINT32_MAX they faill on these backends.

We [changed from int32 to uint32](https://github.com/webmachinelearning/webnn/issues/279) to add the non-negative constraint, but it gaves an extra bit for the dimensions range that's not supported for two of the backends. 

How can we make this better? 

## option 1 - change back to int32
Specifies in spec validation steps that they should be non negative.

## option 2 - keep uint32
Specifies in spec validation steps that they can't exceed INT32_MAX

thoughts? @huningxin @fdwr @inexorabletash

**Comment by inexorabletash** [comment]
Those options seem about equivalent to me. Developers will see the same thing - an exception if they pass a value outside of [0, INT32_MAX]. Same amount of spec work and implementation work in either case I think. And we can relax in the future, e.g. treat negative indices as from the end, or increase to >31 bits if future backends all support it. 

For implementers or future spec authors, I think it might be ever so slightly clearer to specify as (signed) int32, as that means they will probably think _"what does negative mean?"_ and find the notes that explain it, rather than seeing uint32 and just assuming the spec actually allows 32-bit indices. But that's what really WPTs are for.

**Comment by fdwr** [comment]
🤔 I'd rather restrict the range to 2 billion and keep them unsigned than introduce the implication (by adding a sign) that negative dimensions are legal/possible.

> Both CoreML and tflite backends actually use int32_t for dimensions

Is this specifically a TF*Lite* limitation then, as it evidently diverges from the normal TF?

```
    x = tf.ones([65536, 65536])
    print("shape:", x.shape)
    print("dtype:", x.dtype)
    y = tf.reshape(x, [65536 * 65536])
    print("shape:", y.shape)
    print("dtype:", y.dtype)
```
```
shape: (65536, 65536)
dtype: <dtype: 'float32'>
shape: (4294967296,) ✅
dtype: <dtype: 'float32'>
```

There's also ...

## option 3 - keep uint32
Report something like opSupportLimits or WebGPU's [GPUSupportedLimits](https://developer.mozilla.org/en-US/docs/Web/API/GPUSupportedLimits).

I'm not too worried about the limitation in any case though, as it's very unlikely (I've never encountered a case) that you'd have a single tensor with a single dimension greater than 2 billion.

> in the future ... treat negative indices as from the end

😬 Please don't entertain that for dimensions (and axes in general, with the one exception being gather because the data is directly in the tensors). We already intentionally eliminated some of that wiggliness that generally belongs in higher level policies, which should all be resolved to actual values by the time it reaches lower level WebNN.

**Comment by huningxin** [comment]
option 2 - uint32_t with [0, INT32_MAX] range seems a good starter to me. 

The spec can easily put this upper limit into [valid dimension](https://www.w3.org/TR/webnn/#valid-dimension) step and enable the synchronous validation at the renderer side. Then backend implementation (CoreML/TFLite) can cast dimension size to int32_t without asynchronous validation at build time.

Option 2 would also allow us moving to option 3 if needed. WDYT?
