### ISSUE TITLE
Rename MLBuffer => MLTensor

### ISSUE THREAD

**Issue by bbernhar** [webmachinelearning/webnn#753]
The recent revision of the proposed MLBuffer spec no longer represents a low-level concept of device memory storage, as these buffers are now tied to specific shapes and data types. Converting between MLBuffer(s) of different sizes will likely require copying (vs `reinterpret_cast`). To avoid confusion with other 'buffer-as-bytes' types (e.g., GPUBuffer, ArrayBuffer), I propose renaming `MLBuffer` to `MLTensor`.

👍 = I vote yes to rename

**Comment by a-sully** [comment]
SGTM. I've been drafting an explainer for `MLBuffer` and the first sentence is:

> This explainer proposes an `MLBuffer` interface which represents a _tensor_...

I'll find-and-replace and put up the _`MLTensor`_ explainer shortly :D

**Comment by a-sully** [comment]
`MLBuffer` never made it into the spec, so the only artifacts saying "`MLBuffer`" are issues and PRs (and lots of Chromium code which @bbernhar has been diligently refactoring). We could retitle issues including `MLBuffer`. The explainer PR already uses `MLTensor`. Otherwise... I think we can close this? :)

**Comment by bbernhar** [comment]
> I think we can close this? :)

SGTM.
